run-mpi-cart:
	mpicc mpi-cart.c && mpirun -np 8 --oversubscribe a.out

run-mpi-cartsub:
	mpicc mpi-cartsub.c && 	mpirun -np 8 --oversubscribe a.out

run-mpi-even:
	mpicc mpi-even.c && mpirun -np 8 --oversubscribe a.out

run-mpi-split:
	mpicc mpi-split.c && mpirun -np 8 --oversubscribe a.out

run-mpi-matrixvector:
	mpicc mpi-matrixvector.c && mpirun -np 8 --oversubscribe a.out

run-mpi-scalar:
	mpicc mpi-scalar.c && mpirun -np 8 --oversubscribe a.out

run-mpi-pi:
	mpicc mpi-pi.c && echo "3200000" | mpirun -np 8 --oversubscribe a.out



