run-mpi-alive:
	mpicc mpi-alive.c && mpirun -np 2 --oversubscribe a.out
run-mpi-pack:
	mpicc mpi-pack.c &&  mpirun -np 2 --oversubscribe a.out
run-mpi-typevector:
	mpicc mpi-typevector.c && mpirun -np 2 --oversubscribe a.out
run-mpi-hello:
	mpicc mpi-hello.c && mpirun -np 8 --oversubscribe a.out
run-mpi-typestruct:
	mpicc mpi-typestruct.c && mpirun -np 2 --oversubscribe a.out
run-mpi-welcome:
	mpicc mpi-welcome.c && 	mpirun -np 8 --oversubscribe a.out
